general {
    hide_cursor = true
    grace = 500
}

background {
    monitor =
    path = ~/.dotfiles/wallpapers/cyberpunk.jpg

    blur_passes = 2
    blur_size = 1

    brightness = 0.7
    contrast = 1.1
    vibrancy = 0.2
    vibrancy_darkness = 0.5
}

overlay {
    monitor =
    color = rgba(26, 27, 38, 0.85)  # #1a1b26 com transparência
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(122, 162, 247, 1.0)  # #7aa2f7
    font_size = 120
    font_family = JetBrainsMono Nerd Font

    position = 135, 120
    halign = left
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(192, 202, 245, 0.9)  # #c0caf5
    font_size = 26
    font_family = JetBrainsMono Nerd Font

    position = 150, 20
    halign = left
    valign = center
}

input-field {
    monitor =
    size = 350, 50
    outline_thickness = 2
    rounding = 10

    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(220, 220, 220, 1.0)
    inner_color = rgba(0, 0, 0, 0.0)
    font_color = rgba(220, 220, 220, 1.0)

    fade_on_empty = true
    placeholder_text =

    position = 150, -120
    halign = left
    valign = center

}
