max-gamma = 100

profile {
    time = 11:00
    identity = true
}

profile {
    time = 15:00
    temperature = 2500
    gamma = 1.0
}

profile {
    time = 21:00
    temperature = 2000
    gamma = 1.0
}
