# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus
$menu = ~/.config/rofi/launchers/type-2/launcher.sh 
$browser = zen-browser || flatpak run app.zen_browser.zen || firefox
$notes = obsidian || flatpak run md.obsidian.Obsidian
